# Generated by Django 4.0.4 on 2022-06-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='review',
        ),
        migrations.AddField(
            model_name='bookingreview',
            name='booking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='booking_website.booking'),
        ),
    ]
