# Generated by Django 4.0.4 on 2022-06-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bookingreview',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='bookingreview',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='bookingreview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
