# Generated by Django 4.0.4 on 2022-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='booking',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_website_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
