# Generated by Django 4.0.4 on 2022-06-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0002_rename_table_id_booking_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='review',
        ),
    ]
