# Generated by Django 4.0.4 on 2022-06-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0002_remove_restaurant_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_fee_amount',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingfee', to='booking_website.bookingfee'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='subscription_fee_level',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='booking_website.restaurantfees'),
        ),
    ]
