# Generated by Django 4.0.4 on 2022-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0002_remove_restaurant_tables_alter_table_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
