# Generated by Django 4.0.4 on 2022-07-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0003_booking_review_delete_bookingreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_owner',
            new_name='restaurant_owner_id',
        ),
    ]
