# Generated by Django 4.0.4 on 2022-06-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0003_table_is_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='is_booked',
            new_name='booked',
        ),
    ]
