# Generated by Django 4.0.4 on 2022-06-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0003_remove_restaurant_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_fee_amount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingfee', to='booking_website.bookingfee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='booking_website.table'),
        ),
        migrations.AlterField(
            model_name='bookingreview',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='booking_website.booking'),
        ),
        migrations.AlterField(
            model_name='bookingreview',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='booking_website.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking_website.booking'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='.\x07ssets'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='subscription_fee_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='booking_website.restaurantfees'),
        ),
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='booking_website.restaurant'),
        ),
    ]
