# Generated by Django 4.0.4 on 2022-06-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0004_rename_is_booked_table_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
