# Generated by Django 4.0.4 on 2022-06-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0004_alter_booking_booking_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_restaurant', to='booking_website.restaurant'),
        ),
    ]
