# Generated by Django 4.0.4 on 2022-07-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0004_rename_restaurant_owner_restaurant_restaurant_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_owner_id',
            new_name='restaurant_owner',
        ),
    ]
