# Generated by Django 4.0.4 on 2022-06-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0004_alter_booking_booking_fee_amount_alter_booking_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='logo',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='..\\media\x07ssets'),
        ),
    ]
