# Generated by Django 4.0.4 on 2022-07-03 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0005_rename_restaurant_owner_id_restaurant_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
