# Generated by Django 4.0.4 on 2022-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0005_remove_restaurant_logo_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='booking_website/'),
        ),
    ]
