# Generated by Django 4.0.4 on 2022-06-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0005_booking_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_fee_amount',
            new_name='booking_fee_level',
        ),
    ]
