# Generated by Django 4.0.4 on 2022-06-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0005_booking_date_alter_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='participants',
        ),
    ]
