# Generated by Django 4.0.4 on 2022-07-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0006_alter_table_seats_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='QR_code',
            field=models.CharField(max_length=128),
        ),
    ]
