# Generated by Django 4.0.4 on 2022-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0006_remove_booking_card_no_remove_booking_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
