# Generated by Django 4.0.4 on 2022-06-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0007_alter_booking_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingreview',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='booking_website.bookingreview'),
        ),
    ]
