# Generated by Django 4.0.4 on 2022-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_website', '0008_remove_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='QR_code_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='booking_website/bookings'),
        ),
    ]
